# Sample global config for monitoring JHipster applications
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # scheme defaults to 'http'.
    metrics_path: /prometheusMetrics
    
    consul_sd_configs:
    # binds to the consul service container which is part of the docker-compose
      - server: consul:8500
      # - token: <secret> ]
      # - datacenter: <string> ]
      # - scheme: <string> | default = "http"]
      # - username: <string> ]
      # - password: <secret> ]
    relabel_configs:
      # relabels the "instance" label in Targets UI to be equal the name of the consul node
      - source_labels: [__meta_consul_node]
        target_label: instance
        # Following are default values and can be omitted
        regex: '(.*)'
        replacement: $1
        action: replace
      # relabels the "jobs" in Targets UI with the name of the consul service
      - source_labels: [__meta_consul_service]
        target_label: job
