#common configuration shared between all applications
configserver:
    name: Docker JHipster Registry
    status: Connected to Consul running in Docker

jhipster:
    security:
        authentication:
            jwt:
                secret: 418551d8f30051f0467af76c6bc21e7171ff083d

